### PR TITLE
Remove critical vulnerabilities

### PR DESCRIPTION
**Pull request by rjungemann**

### CODE REVIEW

**Comment by Smittyvb** [comment]
What are the "critical vulnerabilities" this fixes?

**Comment by rjungemann** [comment]
* https://github.com/steemit/wallet/network/alert/yarn.lock/macaddress/open
* https://github.com/steemit/wallet/network/alert/blackboxtest/yarn.lock/growl/open

**Comment by Smittyvb** [comment]
@rjungemann ??? Those links 404

**Comment by rjungemann** [comment]
I don't know why that is the case. Here is the text output.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.2.9                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ css-loader                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ css-loader > cssnano > postcss-filter-plugins > uniqid >     │
│               │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/654                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.2.9                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @storybook/react                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @storybook/react > css-loader > cssnano >                    │
│               │ postcss-filter-plugins > uniqid > macaddress                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/654                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Pull request merged**
